import { Router } from "express"; import { z } from "zod"; import { requireAuth, requireBot } from "../middleware/auth";
import { areGuildRoles } from "../services/discordOptionsService"; import { authorizeBotRuntimeModule, canReadDevBotModule, canUseDevBotModule, getBotApiPermissions, getDevBotToken } from "../services/devBotService"; import { resolveRequestBotId } from "../services/requestBotScopeService"; import { getAutomatedLogSettings, saveAutomatedLogSettings, updateAutomatedLogRuntime } from "../services/automatedLogService"; import type { AuthSessionUser } from "../types/session";
const guild = z.string().regex(/^\d{5,32}$/); const id = guild; const channels = z.object({ site: id.nullable(), absence: id.nullable(), messages: id.nullable(), calls: id.nullable(), verification: id.nullable(), punishment: id.nullable() });
export const automatedLogsRouter = Router();
automatedLogsRouter.get("/bot/:guildId", requireBot, async (req,res,next)=>{try{const s=await botScope(req,req.params.guildId);return res.json({settings:await getAutomatedLogSettings(s.botId,s.guildId)});}catch(e){return next(e);}});
automatedLogsRouter.patch("/bot/:guildId/runtime", requireBot, async (req,res,next)=>{try{const s=await botScope(req,req.params.guildId);const input=z.object({categoryId:id.nullable().optional(),channels:channels.optional(),lastError:z.string().max(1000).nullable().optional(),synced:z.boolean().optional()}).parse(req.body);return res.json({settings:await updateAutomatedLogRuntime(s.botId,s.guildId,input)});}catch(e){return next(e);}});
automatedLogsRouter.get("/:guildId", requireAuth, async(req,res,next)=>{try{const s=await userScope(req,res.locals.dashboardAuth.user,req.params.guildId,false);return res.json({settings:await getAutomatedLogSettings(s.botId,s.guildId)});}catch(e){return next(e);}});
automatedLogsRouter.patch("/:guildId", requireAuth, async(req,res,next)=>{try{const user=res.locals.dashboardAuth.user as AuthSessionUser;const s=await userScope(req,user,req.params.guildId,true);const input=z.object({enabled:z.boolean().optional(),allowedRoleIds:z.array(id).max(100).optional()}).parse(req.body);if(input.allowedRoleIds?.length&&!await areGuildRoles(s.guildId,input.allowedRoleIds,await getDevBotToken(s.botId)))throw err("Um dos cargos autorizados a ver logs não pertence a este servidor.",400);return res.json({settings:await saveAutomatedLogSettings(s.botId,s.guildId,input)});}catch(e){return next(e);}});
automatedLogsRouter.post("/:guildId/sync", requireAuth, async(req,res,next)=>{try{const s=await userScope(req,res.locals.dashboardAuth.user,req.params.guildId,true);return res.json({settings:await saveAutomatedLogSettings(s.botId,s.guildId,{},true)});}catch(e){return next(e);}});
async function botScope(req:Parameters<typeof resolveRequestBotId>[0],raw:unknown){const guildId=guild.parse(raw);const botId=await resolveRequestBotId(req);if(!botId)throw err("Escopo do bot é obrigatório.",400);const p=await getBotApiPermissions(botId);if(!p?.enabledModules.includes("logs"))throw err("Logs não estão ativados para este bot.",403);const a=await authorizeBotRuntimeModule({botId,guildId,moduleId:"logs"});if(!a.allowed)throw err(a.reason,403);return{botId,guildId};}
async function userScope(req:Parameters<typeof resolveRequestBotId>[0],user:AuthSessionUser,raw:unknown,manage:boolean){const guildId=guild.parse(raw);const botId=await resolveRequestBotId(req);if(!botId)throw err("Selecione um bot cadastrado.",400);const ok=manage?await canUseDevBotModule(user,botId,guildId,"logs"):await canReadDevBotModule(user,botId,guildId,"logs");if(!ok)throw err("Você não tem permissão para configurar este sistema de logs.",403);return{botId,guildId};}
function err(message:string,statusCode:number){return Object.assign(new Error(message),{statusCode});}
