import { Router } from "express";
import { z } from "zod";
import { requireAuth, requireBot } from "../middleware/auth";
import { canReadDevBotModule, canUseDevBotModule } from "../services/devBotService";
import { resolveRequestBotId } from "../services/requestBotScopeService";
import { createPd7Request, getPd7Dashboard, getPd7Request, listActivePd7Settings, listPd7Settings, requestPd7Publish, savePd7Settings, updatePd7PanelState, updatePd7Request } from "../services/fivemPd7Service";

const snowflake = z.string().regex(/^\d{5,32}$/); const id = z.string().min(1).max(80);
const field = z.object({ id: id.regex(/^[a-z0-9_-]+$/i), label: z.string().min(1).max(45), placeholder: z.string().max(100).nullable(), required: z.boolean(), style: z.enum(["short","paragraph"]), order: z.number().int().min(0).max(4) });
const settings = z.object({ factionName: z.string().min(1).max(80).optional(), enabled: z.boolean().optional(), categoryPD7: snowflake.nullable().optional(), panelChannelPD7: snowflake.nullable().optional(), logChannelPD7: snowflake.nullable().optional(), allowedRolesPD7: z.array(snowflake).max(100).optional(), responsibleUsersPD7: z.array(snowflake).max(100).optional(), approvedRolePD7: snowflake.nullable().optional(), rejectedRolePD7: snowflake.nullable().optional(), fields: z.array(field).min(1).max(5).optional(), autoDeleteMinutes: z.number().int().min(0).max(43200).nullable().optional() });
export const fivemPd7Router = Router();
async function scope(req: any, res: any, manage: boolean) { const botId = await resolveRequestBotId(req); if (!botId) throw Object.assign(new Error("Selecione um bot DEV."),{statusCode:400}); const guildId = snowflake.parse(req.params.guildId); const ok = manage ? await canUseDevBotModule(res.locals.dashboardAuth.user,botId,guildId,"fivem-factions") : await canReadDevBotModule(res.locals.dashboardAuth.user,botId,guildId,"fivem-factions"); if (!ok) throw Object.assign(new Error("Sem permissão para o sistema de Facções."),{statusCode:403}); return {botId,guildId}; }
fivemPd7Router.get("/:guildId",requireAuth,async(req,res,next)=>{try{const s=await scope(req,res,false); return res.json({factions:await listPd7Settings(s.guildId,s.botId)});}catch(e){next(e)}});
fivemPd7Router.get("/:guildId/factions/:factionId",requireAuth,async(req,res,next)=>{try{const s=await scope(req,res,false); return res.json(await getPd7Dashboard(s.guildId,s.botId,id.parse(req.params.factionId)));}catch(e){next(e)}});
fivemPd7Router.patch("/:guildId/factions/:factionId",requireAuth,async(req,res,next)=>{try{const s=await scope(req,res,true); return res.json({settings:await savePd7Settings(s.guildId,s.botId,id.parse(req.params.factionId),settings.parse(req.body))});}catch(e){next(e)}});
fivemPd7Router.post("/:guildId/factions/:factionId/publish",requireAuth,async(req,res,next)=>{try{const s=await scope(req,res,true); return res.json({settings:await requestPd7Publish(s.guildId,s.botId,id.parse(req.params.factionId))});}catch(e){next(e)}});
fivemPd7Router.get("/bot/configs",requireBot,async(req,res,next)=>{try{const botId=await resolveRequestBotId(req); if(!botId) throw Error("Bot inválido"); return res.json({configs:await listActivePd7Settings(botId)});}catch(e){next(e)}});
fivemPd7Router.post("/bot/requests",requireBot,async(req,res,next)=>{try{const botId=await resolveRequestBotId(req); if(!botId) throw Error("Bot inválido"); const input=z.object({guildId:snowflake,factionId:id,userId:snowflake,username:z.string().max(100),fields:z.array(z.object({id,label:z.string().max(45),value:z.string().max(4000)})).max(5)}).parse(req.body); return res.status(201).json({request:await createPd7Request({...input,botId})});}catch(e){next(e)}});
fivemPd7Router.get("/bot/requests/:requestId",requireBot,async(req,res,next)=>{try{const botId=await resolveRequestBotId(req); const request=botId&&await getPd7Request(id.parse(req.params.requestId),botId); return request?res.json({request}):res.status(404).json({message:"PD7 não encontrado."});}catch(e){next(e)}});
fivemPd7Router.patch("/bot/requests/:requestId",requireBot,async(req,res,next)=>{try{const botId=await resolveRequestBotId(req); if(!botId) throw Error("Bot inválido"); const patch=z.object({status:z.enum(["pending","approved","rejected","closed"]).optional(),channelId:snowflake.nullable().optional(),panelMessageId:snowflake.nullable().optional(),handledBy:snowflake.nullable().optional(),rejectionReason:z.string().max(1000).nullable().optional(),resolvedAt:z.coerce.date().nullable().optional()}).parse(req.body); return res.json({request:await updatePd7Request(id.parse(req.params.requestId),botId,patch)});}catch(e){next(e)}});
fivemPd7Router.post("/bot/panel-state",requireBot,async(req,res,next)=>{try{const botId=await resolveRequestBotId(req); if(!botId) throw Error("Bot inválido"); const input=z.object({guildId:snowflake,factionId:id,panelMessageId:snowflake.nullable()}).parse(req.body); return res.json({settings:await updatePd7PanelState(input.guildId,botId,input.factionId,input.panelMessageId)});}catch(e){next(e)}});
