import { Router } from "express";
import { advancedModulesRouter } from "./advancedModules";
import { antiBanBotRouter, antiBanDashboardRouter } from "./antiBan";
import { authRouter } from "./auth";
import { autoActivityClockRouter } from "./autoActivityClock";
import { automatedLogsRouter } from "./automatedLogs";
import { boostersRouter } from "./boosters";
import { botDevApiRouter } from "./botDevApi";
import { clipsRouter } from "./clips";
import { contractsRouter } from "./contracts";
import { coursesRouter } from "./courses";
import { customBotOrdersRouter } from "./customBotOrders";
import { dafScaleRouter } from "./dafScale";
import { dashboardRouter } from "./dashboard";
import { databaseMaintenanceRouter } from "./databaseMaintenance";
import { devRouter } from "./dev";
import { dmBarRouter } from "./dmBar";
import { emojiClonerRouter } from "./emojiCloner";
import { factionChestRouter } from "./factionChest";
import { fivemRouter } from "./fivem";
import { fivemActionsRouter } from "./fivemActions";
import { fivemFinanceRouter } from "./fivemFinance";
import { fivemOrdersRouter } from "./fivemOrders";
import { fivemPd7Router } from "./fivemPd7";
import { giveawaysRouter } from "./giveaways";
import { globalBlacklistRouter } from "./globalBlacklist";
import { guildsRouter } from "./guilds";
import { healthRouter } from "./health";
import { imageAntiSpamRouter } from "./imageAntiSpam";
import { invitePagesRouter } from "./invitePages";
import { kickNotificationsRouter, kickWebhookRouter } from "./kickNotifications";
import { livesRouter } from "./lives";
import { logsRouter } from "./logs";
import { manualPaymentsRouter } from "./manualPayments";
import { manualRegistrationRouter } from "./manualRegistration";
import { mediaRouter } from "./media";
import { messageControlRouter } from "./messageControl";
import { metaWorkflowRouter } from "./metaWorkflow";
import { missionToolsRouter } from "./missionTools";
import { nexTechSalesRouter } from "./nexTechSales";
import { openDutyNotificationsRouter } from "./openDutyNotifications";
import { panelImagesRouter } from "./panelImages";
import { panelsRouter } from "./panels";
import { paymentGatewayRouter } from "./paymentGateway";
import { paymentAdminRouter, paymentsRouter, paymentWebhooksRouter, subscriptionsPaymentsRouter } from "./payments";
import { persistentImagesRouter } from "./persistentImages";
import { botRegistrationRouter, checkoutRouter, customerPlansRouter, plansRouter, workspacePlansRouter } from "./plans";
import { policeHiddenChannelRouter } from "./policeHiddenChannel";
import { policePatrolReportsRouter } from "./policePatrolReports";
import { policePromotionsRouter } from "./policePromotions";
import { policeQruRouter } from "./policeQru";
import { policeTimeClockRouter } from "./policeTimeClock";
import { priceTablesRouter } from "./priceTables";
import { publicStatusRouter } from "./publicStatus";
import { reportForwardingRouter } from "./reportForwarding";
import { rhAdminRouter } from "./rhAdmin";
import { selfBotProtectionRouter } from "./selfBotProtection";
import { serverBackupsRouter } from "./serverBackups";
import { settingsRouter } from "./settings";
import { botLivesRouter, socialNotificationsRouter } from "./socialNotifications";
import { socialsRouter } from "./socials";
import { statusRouter } from "./status";
import { subscriptionPresenceRouter } from "./subscriptionPresence";
import { temporaryVoiceRouter } from "./temporaryVoice";
import { ticketsRouter } from "./tickets";
import { transcriptsRouter } from "./transcripts";
import { usersRouter } from "./users";
import { vehicleAbandonmentRouter } from "./vehicleAbandonment";
import { visibleMessageRouter } from "./visibleMessage";
import { voiceRecorderRouter } from "./voiceRecorder";
import { xMonitorRouter } from "./xMonitor";
import { xWebhookRouter } from "./xWebhook";
import { ztkWebhookRouter } from "./ztkWebhook";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/advanced-modules", advancedModulesRouter);
apiRouter.use("/anti-ban", antiBanBotRouter);
apiRouter.use("/image-anti-spam", imageAntiSpamRouter);
apiRouter.use("/invite", invitePagesRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/automated-logs", automatedLogsRouter);
apiRouter.use("/auto-activity-clock", autoActivityClockRouter);
apiRouter.use("/boosters", boostersRouter);
apiRouter.use("/bot", botDevApiRouter);
apiRouter.use("/bots", botLivesRouter);
apiRouter.use("/bots", antiBanDashboardRouter);
apiRouter.use("/clips", clipsRouter);
apiRouter.use("/contracts", contractsRouter);
apiRouter.use("/courses", coursesRouter);
apiRouter.use("/custom-bot-orders", customBotOrdersRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/database-maintenance", databaseMaintenanceRouter);
apiRouter.use("/daf-scale", dafScaleRouter);
apiRouter.use("/dev", devRouter);
apiRouter.use("/dm-bar", dmBarRouter);
apiRouter.use("/emoji-cloner", emojiClonerRouter);
apiRouter.use("/fivem", fivemRouter);
apiRouter.use("/fivem-pd7", fivemPd7Router);
apiRouter.use("/fivem-actions", fivemActionsRouter);
apiRouter.use("/fivem-finance", fivemFinanceRouter);
apiRouter.use("/faction-chests", factionChestRouter);
apiRouter.use("/global-blacklist", globalBlacklistRouter);
apiRouter.use("/giveaways", giveawaysRouter);
apiRouter.use("/kick", kickWebhookRouter);
apiRouter.use("/kick-integration", kickNotificationsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/guilds", guildsRouter);
apiRouter.use("/lives", livesRouter);
apiRouter.use("/mission-tools", missionToolsRouter);
apiRouter.use("/nex-tech-sales", nexTechSalesRouter);
apiRouter.use("/open-duty-notifications", openDutyNotificationsRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/panel-images", panelImagesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/subscriptions", subscriptionsPaymentsRouter);
apiRouter.use("/payment-gateway", paymentGatewayRouter);
apiRouter.use("/panels", panelsRouter);
apiRouter.use("/admin/payments", paymentAdminRouter);
apiRouter.use("/webhooks", paymentWebhooksRouter);
apiRouter.use("/plans", plansRouter);
apiRouter.use("/public", publicStatusRouter);
apiRouter.use("/checkout", checkoutRouter);
apiRouter.use("/bot-registration", botRegistrationRouter);
apiRouter.use("/customer", customerPlansRouter);
apiRouter.use("/workspaces", workspacePlansRouter);
apiRouter.use("/police-patrol-reports", policePatrolReportsRouter);
apiRouter.use("/police-hidden-channel", policeHiddenChannelRouter);
apiRouter.use("/police-promotions", policePromotionsRouter);
apiRouter.use("/police-qru", policeQruRouter);
apiRouter.use("/police-time-clock", policeTimeClockRouter);
apiRouter.use("/price-tables", priceTablesRouter);
apiRouter.use("/persistent-images", persistentImagesRouter);
apiRouter.use("/report-forwarding", reportForwardingRouter);
apiRouter.use("/rh-admin", rhAdminRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/transcripts", transcriptsRouter);
apiRouter.use("/temporary-voice", temporaryVoiceRouter);
apiRouter.use("/vehicle-abandonment", vehicleAbandonmentRouter);
apiRouter.use("/voice-recorder", voiceRecorderRouter);
apiRouter.use("/visible-message", visibleMessageRouter);
apiRouter.use("/logs", logsRouter);
apiRouter.use("/manual-registration", manualRegistrationRouter);
apiRouter.use("/manual-payments", manualPaymentsRouter);
apiRouter.use("/message-control", messageControlRouter);
apiRouter.use("/meta-workflow", metaWorkflowRouter);
apiRouter.use("/fivem-orders", fivemOrdersRouter);
apiRouter.use("/self-bot-protection", selfBotProtectionRouter);
apiRouter.use("/server-backups", serverBackupsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/social-notifications", socialNotificationsRouter);
apiRouter.use("/socials", socialsRouter);
apiRouter.use("/status", statusRouter);
apiRouter.use("/payment-presence", subscriptionPresenceRouter);
apiRouter.use("/subscription-presence", subscriptionPresenceRouter);
apiRouter.use("/x-monitor", xMonitorRouter);
apiRouter.use("/x-webhook", xWebhookRouter);
apiRouter.use("/ztk-webhook", ztkWebhookRouter);
