import { ChannelType, PermissionFlagsBits, type Client, type Guild, type GuildBasedChannel } from "discord.js";
import type { BotContext } from "../types";
import type { AutomatedLogSettings } from "./apiClient";

const CATEGORY_NAME = "[Skyfall] - Logs";
const CHANNELS = { site: "logs-site", absence: "logs-ausência", messages: "logs-msg", calls: "logs-call", verification: "verificação-dc", punishment: "logs-punição" } as const;
let started = false;
const lastValidationAt = new Map<string, number>();
const lastAttemptAt = new Map<string, number>();
export function startAutomatedLogService(client: Client<true>, context: BotContext) { if (started) return; started = true; void reconcileAll(client, context); const timer=setInterval(()=>void reconcileAll(client,context),60_000);timer.unref(); }
async function reconcileAll(client:Client<true>,context:BotContext){for(const guild of client.guilds.cache.values()){const settings=await context.api.getAutomatedLogSettings(guild.id).catch(()=>null);if(!settings?.enabled)continue;const requested=!settings.lastSyncedAt||Boolean(settings.lastSyncRequestedAt&&settings.lastSyncRequestedAt>settings.lastSyncedAt);const missingIds=!settings.categoryId||Object.values(settings.channels).some((id)=>!id);const retryDue=(lastAttemptAt.get(guild.id)??0)<Date.now()-300_000;let shouldSync=requested||(!settings.lastError&&missingIds)||(Boolean(settings.lastError)&&retryDue);if(!shouldSync&&(lastValidationAt.get(guild.id)??0)<Date.now()-300_000){lastValidationAt.set(guild.id,Date.now());const ids=[settings.categoryId,...Object.values(settings.channels)].filter(Boolean) as string[];const existing=await Promise.all(ids.map((id)=>guild.channels.fetch(id).catch(()=>null)));shouldSync=existing.some((channel)=>!channel);}if(shouldSync){lastAttemptAt.set(guild.id,Date.now());await reconcileGuild(guild,context,settings,requested||missingIds).catch(async(error)=>{const message=error instanceof Error?error.message:String(error);console.warn(`[automated-logs] ${guild.id}: ${message}`);await context.api.updateAutomatedLogRuntime(guild.id,{lastError:message}).catch(()=>null);});}}}
async function reconcileGuild(guild:Guild,context:BotContext,settings:AutomatedLogSettings,refreshPermissions:boolean){const me=guild.members.me;if(!me?.permissions.has(PermissionFlagsBits.ManageChannels))throw new Error("The bot lacks Manage Channels permission.");const all=await guild.channels.fetch();let category=settings.categoryId?all.get(settings.categoryId):null;if(category?.type!==ChannelType.GuildCategory)category=all.find((channel)=>channel?.type===ChannelType.GuildCategory&&channel.name===CATEGORY_NAME)??null;if(!category)category=await guild.channels.create({name:CATEGORY_NAME,type:ChannelType.GuildCategory,permissionOverwrites:overwrites(guild,settings)});else if(refreshPermissions)await category.permissionOverwrites.set(overwrites(guild,settings),"Synchronize automated log permissions");const resolved={...settings.channels};for(const [key,name] of Object.entries(CHANNELS) as Array<[keyof typeof CHANNELS,string]>){let channel=resolved[key]?all.get(resolved[key]!):null;if(channel?.type!==ChannelType.GuildText||channel.parentId!==category.id)channel=all.find((item)=>item?.type===ChannelType.GuildText&&item.parentId===category.id&&item.name===name)??null;if(!channel)channel=await guild.channels.create({name,type:ChannelType.GuildText,parent:category.id,permissionOverwrites:overwrites(guild,settings)});else if(refreshPermissions)await channel.permissionOverwrites.set(overwrites(guild,settings),"Synchronize automated log permissions");resolved[key]=channel.id;}await context.api.updateAutomatedLogRuntime(guild.id,{categoryId:category.id,channels:resolved,lastError:null,synced:true});}
function overwrites(guild:Guild,settings:AutomatedLogSettings){const list:Array<{id:string;allow?:bigint[];deny?:bigint[]}>=[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]}];if(guild.client.user)list.push({id:guild.client.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.EmbedLinks,PermissionFlagsBits.ManageChannels,PermissionFlagsBits.ReadMessageHistory]});for(const roleId of settings.allowedRoleIds)list.push({id:roleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ReadMessageHistory]});return list;}

export function automatedLogChannelForType(settings:AutomatedLogSettings,type:string){const value=type.toLowerCase();if(value.startsWith("message.")||value.includes("spam")||value.includes("link"))return settings.channels.messages;if(value.startsWith("voice.")||value.includes("call"))return settings.channels.calls;if(value.includes("verification"))return settings.channels.verification;if(value.includes("absence")||value.includes("ausencia")||value.includes("fivem.fac"))return settings.channels.absence;if(value.includes("warning")||value.includes("punish")||value.includes("moderation")||value.includes("security")||value.includes("self_bot")||value.includes("anti-ban"))return settings.channels.punishment;return settings.channels.site;}
